# Generated by Django 4.1.5 on 2023-01-31 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0003_customuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='unique_id',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
