# Generated by Django 4.1.5 on 2023-03-09 18:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0007_customuser_online_status_alter_chatmessage_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='last_seen',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 9, 23, 47, 5, 998289)),
        ),
    ]
