# Generated by Django 4.1.5 on 2023-04-02 17:30

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0009_chatmessage_file_type_chatmessage_message_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SymmetricKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=500)),
            ],
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_seen',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 2, 23, 0, 19, 860788)),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='encryption_key',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='chatapp.symmetrickey'),
            preserve_default=False,
        ),
    ]
