# Generated by Django 4.1.5 on 2023-04-04 07:10

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chatapp', '0011_remove_chatmessage_encryption_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='received_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_seen',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 4, 12, 40, 37, 46284)),
        ),
    ]
